[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
onchain_verified_nft_collection = "HdSXhd8wmPH9VsTxSAaNyaw3CCXMcCHis9SH3CZtELdJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/wba-wallet.json"

[scripts]
test-nft-collection = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/onchain-verified-nft-collection.ts"